### PR TITLE
Fix #80

### LINKED ISSUE #80: Loading the element async produces undefined errors
I'm not sure the root cause of this issue but here's what I've been able to dig up.

When I load the element async and it has a condenses attribute, the `condensesChanged` observer runs immediately, causing `_updateScrollState` to run. In this function, the `ctx` object is undefined, so checks [like this](https://github.com/PolymerElements/paper-scroll-header-panel/blob/master/paper-scroll-header-panel.html#L560) fail and cause an error. It seems like the `Polymer.PaperScrollHeaderPanel` property has not had a chance to be created when that observer fires. Using `this.async` inside of `_updateScrollState` seems to fix the issue.

### PR DESCRIPTION
**Pull request by blasten**
It's not awesome, but it won't break the current expected behavior.

### CODE REVIEW

**Comment by blasten** [comment]
@addyosmani I'm gonna talk to @sorvell about this issue.

**Comment by blasten** [comment]
@addyosmani would you mind sending me an example of how you may want to create an instance using `Polymer.PaperScrollHeaderPanel` while the right-hand side of the `Polymer.PaperScrollHeaderPanel =..` statement hasn't returned? It seems like you could get around the issue by using `this.async`. I know it's not awesome.

**Comment by blasten** [comment]
friendly ping @addyosmani

**Comment by frankiefu** [comment]
lgtm

**Pull request merged**
